import { useMemo, useState } from "react";

export type LearningJournalItem = {
  learningJournalId: number;
  lessonKey: string;
  title: string;
  summary: string;
  preventionRule: string;
  category: "intent" | "context" | "grounding" | "workflow" | "tone" | "conversation";
  status: "active" | "deleted";
  autoGenerated: boolean;
  timesObserved: number;
  lastObservedAt: string;
  createdAt: string;
  updatedAt: string;
};

export type LearningJournalDraft = {
  title: string;
  summary: string;
  preventionRule: string;
  category: LearningJournalItem["category"];
};

type Props = {
  items: LearningJournalItem[];
  busy?: string;
  onSave: (id: number, payload: LearningJournalDraft) => Promise<void>;
  onDelete: (item: LearningJournalItem) => Promise<void>;
};

const categoryLabel: Record<LearningJournalItem["category"], string> = {
  intent: "Nhận dạng ý định",
  context: "Giữ ngữ cảnh",
  grounding: "Bám dữ liệu thật",
  workflow: "Luồng nghiệp vụ",
  tone: "Cách phản hồi",
  conversation: "Hội thoại",
};

const formatDate = (value?: string) => {
  if (!value) return "—";
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? "—"
    : new Intl.DateTimeFormat("vi-VN", {
        dateStyle: "short",
        timeStyle: "short",
      }).format(date);
};

export default function LearningJournalPanel({ items, busy, onSave, onDelete }: Props) {
  const [editingId, setEditingId] = useState<number | null>(null);
  const [drafts, setDrafts] = useState<Record<number, LearningJournalDraft>>({});

  const activeDraft = useMemo(
    () => (editingId ? drafts[editingId] : undefined),
    [drafts, editingId],
  );

  const startEdit = (item: LearningJournalItem) => {
    setEditingId(item.learningJournalId);
    setDrafts((current) => ({
      ...current,
      [item.learningJournalId]: current[item.learningJournalId] ?? {
        title: item.title,
        summary: item.summary,
        preventionRule: item.preventionRule,
        category: item.category,
      },
    }));
  };

  const updateDraft = (id: number, patch: Partial<LearningJournalDraft>) => {
    setDrafts((current) => ({
      ...current,
      [id]: {
        title: current[id]?.title ?? "",
        summary: current[id]?.summary ?? "",
        preventionRule: current[id]?.preventionRule ?? "",
        category: current[id]?.category ?? "conversation",
        ...patch,
      },
    }));
  };

  return (
    <section className="agent-admin__subsection agent-admin__memory-panel learning-journal-safe">
      <header>
        <div>
          <h2>Nhật ký AI tự học</h2>
          <p>
            AI chỉ ghi lại bài học tổng quát khi phát hiện mình hiểu sai hoặc được người dùng sửa.
            Nhật ký này không hiển thị hồ sơ, bộ nhớ cá nhân hay nội dung chat của từng người dùng.
            Các bài học đang hoạt động được đưa lại vào prompt như quy tắc hành vi để tránh lặp lỗi,
            không được xem là tri thức nghiệp vụ hay tự thay đổi giá/chính sách.
          </p>
        </div>
        <small>{items.length} bài học đang hoạt động</small>
      </header>

      <div
        className="agent-admin__memory-scroll"
        role="region"
        aria-label="Danh sách bài học tự rút ra của AI"
      >
        {items.map((item) => {
          const isEditing = editingId === item.learningJournalId;
          const draft = drafts[item.learningJournalId];
          return (
            <article className="agent-admin__memory-card" key={item.learningJournalId}>
              <div className="agent-admin__memory-head">
                <div>
                  <div className="agent-admin__memory-badges">
                    <span className="agent-admin__status status-active">Đang áp dụng</span>
                    <span>{categoryLabel[item.category]}</span>
                    <span>{item.autoGenerated ? "AI tự rút bài học" : "Đã được quản trị viên chỉnh"}</span>
                    {item.timesObserved > 1 && <span>Lặp lại {item.timesObserved} lần</span>}
                  </div>
                  <h4>{item.title}</h4>
                  <p>
                    Ghi nhận gần nhất: {formatDate(item.lastObservedAt)} · Cập nhật: {formatDate(item.updatedAt)}
                  </p>
                </div>
              </div>

              {isEditing ? (
                <div className="agent-admin__memory-edit-grid">
                  <label className="agent-admin__review-field">
                    <span>Tên bài học</span>
                    <input
                      maxLength={220}
                      type="text"
                      value={draft?.title ?? ""}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, { title: event.target.value })
                      }
                    />
                  </label>
                  <label className="agent-admin__review-field">
                    <span>Nhóm lỗi</span>
                    <select
                      value={draft?.category ?? item.category}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, {
                          category: event.target.value as LearningJournalItem["category"],
                        })
                      }
                    >
                      {Object.entries(categoryLabel).map(([value, label]) => (
                        <option key={value} value={value}>{label}</option>
                      ))}
                    </select>
                  </label>
                  <label className="agent-admin__review-field agent-admin__review-field--full">
                    <span>AI đã học được gì?</span>
                    <textarea
                      maxLength={3000}
                      rows={3}
                      value={draft?.summary ?? ""}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, { summary: event.target.value })
                      }
                    />
                  </label>
                  <label className="agent-admin__review-field agent-admin__review-field--full">
                    <span>Quy tắc tránh lặp lại</span>
                    <textarea
                      maxLength={3000}
                      rows={3}
                      value={draft?.preventionRule ?? ""}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, { preventionRule: event.target.value })
                      }
                    />
                  </label>
                </div>
              ) : (
                <div className="agent-admin__memory-body learning-journal-safe__body">
                  <div>
                    <strong>AI đã học được gì?</strong>
                    <p>{item.summary}</p>
                  </div>
                  <div>
                    <strong>Quy tắc tránh lặp lại</strong>
                    <p>{item.preventionRule}</p>
                  </div>
                </div>
              )}

              <div className="agent-admin__memory-actions">
                {isEditing ? (
                  <>
                    <button
                      disabled={busy === `learning-journal-save-${item.learningJournalId}` || !activeDraft}
                      onClick={() =>
                        onSave(
                          item.learningJournalId,
                          draft ?? {
                            title: item.title,
                            summary: item.summary,
                            preventionRule: item.preventionRule,
                            category: item.category,
                          },
                        ).then(() => setEditingId(null))
                      }
                      type="button"
                    >
                      Lưu bài học
                    </button>
                    <button onClick={() => setEditingId(null)} type="button">Hủy</button>
                  </>
                ) : (
                  <button onClick={() => startEdit(item)} type="button">Sửa</button>
                )}
                <button
                  className="danger"
                  disabled={busy === `learning-journal-delete-${item.learningJournalId}`}
                  onClick={() => onDelete(item)}
                  type="button"
                >
                  Xóa bài học
                </button>
              </div>
            </article>
          );
        })}

        {!items.length && (
          <div className="agent-admin__empty">
            Chưa có bài học tự động nào. Khi AI bị người dùng sửa hoặc phát hiện mình hiểu sai,
            bài học đã khử dữ liệu cá nhân sẽ xuất hiện ở đây.
          </div>
        )}
      </div>
    </section>
  );
}
