import { useMemo, useState } from "react";
import { Check, Pencil, Save, Trash2, X } from "lucide-react";

export type LearningJournalItem = {
  learningJournalId: number;
  lessonKey: string;
  title: string;
  summary: string;
  preventionRule: string;
  category: "intent" | "context" | "grounding" | "workflow" | "tone" | "conversation";
  status: "active" | "deleted";
  autoGenerated: boolean;
  timesObserved: number;
  lastObservedAt: string;
  createdAt: string;
  updatedAt: string;
  isPromptActive?: boolean;
  reviewStatus?: "pending" | "auto_approved" | "admin_approved";
  knowledgeEntryId?: number | null;
  evaluatorModel?: string | null;
  evaluationReason?: string | null;
  evaluatedAt?: string | null;
};

export type LearningJournalDraft = {
  title: string;
  summary: string;
  preventionRule: string;
  category: LearningJournalItem["category"];
};

type Props = {
  items: LearningJournalItem[];
  busy?: string;
  onApprove: (item: LearningJournalItem) => Promise<void>;
  onSave: (id: number, payload: LearningJournalDraft) => Promise<void>;
  onDelete: (item: LearningJournalItem) => Promise<void>;
};

const categoryLabel: Record<LearningJournalItem["category"], string> = {
  intent: "Nhận dạng ý định",
  context: "Giữ ngữ cảnh",
  grounding: "Bám dữ liệu thật",
  workflow: "Luồng nghiệp vụ",
  tone: "Cách phản hồi",
  conversation: "Hội thoại",
};

const formatDate = (value?: string) => {
  if (!value) return "—";
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? "—"
    : new Intl.DateTimeFormat("vi-VN", {
        dateStyle: "short",
        timeStyle: "short",
      }).format(date);
};

export default function LearningJournalPanel({ items, busy, onApprove, onSave, onDelete }: Props) {
  const [editingId, setEditingId] = useState<number | null>(null);
  const [drafts, setDrafts] = useState<Record<number, LearningJournalDraft>>({});

  const activeDraft = useMemo(
    () => (editingId ? drafts[editingId] : undefined),
    [drafts, editingId],
  );

  const startEdit = (item: LearningJournalItem) => {
    setEditingId(item.learningJournalId);
    setDrafts((current) => ({
      ...current,
      [item.learningJournalId]: current[item.learningJournalId] ?? {
        title: item.title,
        summary: item.summary,
        preventionRule: item.preventionRule,
        category: item.category,
      },
    }));
  };

  const updateDraft = (id: number, patch: Partial<LearningJournalDraft>) => {
    setDrafts((current) => ({
      ...current,
      [id]: {
        title: current[id]?.title ?? "",
        summary: current[id]?.summary ?? "",
        preventionRule: current[id]?.preventionRule ?? "",
        category: current[id]?.category ?? "conversation",
        ...patch,
      },
    }));
  };

  return (
    <section className="agent-admin__subsection agent-admin__memory-panel learning-journal-safe">
      <header>
        <div>
          <h2>Nhật ký AI tự học</h2>
          <p>
            AI chỉ ghi lại bài học tổng quát khi phát hiện mình hiểu sai hoặc được người dùng sửa.
            Nhật ký này không hiển thị hồ sơ, bộ nhớ cá nhân hay nội dung chat của từng người dùng.
            AI tự thẩm định các bài học về giao tiếp, ứng xử và giữ ngữ cảnh.
            Bài học đạt yêu cầu được đưa vào Kho tri thức; nội dung liên quan giá, chính sách,
            quyền hạn hoặc workflow vẫn phải chờ quản trị viên duyệt.
          </p>
        </div>
        <small>{items.length} bài học đang hoạt động</small>
      </header>

      <div
        className="agent-admin__memory-scroll"
        role="region"
        aria-label="Danh sách bài học tự rút ra của AI"
      >
        {items.map((item) => {
          const isEditing = editingId === item.learningJournalId;
          const draft = drafts[item.learningJournalId];
          const isPromptActive =
            item.isPromptActive ??
            (!item.autoGenerated ||
              item.reviewStatus === "auto_approved" ||
              item.reviewStatus === "admin_approved" ||
              Boolean(item.knowledgeEntryId));
          return (
            <article
              className="agent-admin__memory-card learning-journal-safe__card"
              key={item.learningJournalId}
            >
              <div className="agent-admin__memory-head learning-journal-safe__head">
                <div className="learning-journal-safe__heading">
                  <div className="agent-admin__memory-badges">
                    <span>{categoryLabel[item.category]}</span>
                    <span>{item.autoGenerated ? "AI tự rút bài học" : "Đã được quản trị viên chỉnh"}</span>
                    {item.timesObserved > 1 && <span>Lặp lại {item.timesObserved} lần</span>}
                  </div>
                  <h4>{item.title}</h4>
                  <p>
                    Ghi nhận gần nhất: {formatDate(item.lastObservedAt)} · Cập nhật: {formatDate(item.updatedAt)}
                  </p>
                  {item.evaluationReason && (
                    <p className="learning-journal-safe__evaluation">
                      Nhận xét: {item.evaluationReason}
                    </p>
                  )}
                </div>
                <div className="learning-journal-safe__status-group">
                  <span
                    className={`agent-admin__status learning-journal-safe__status ${isPromptActive ? "status-active" : "status-quarantined"}`}
                  >
                    {isPromptActive ? "Đang được sử dụng" : "Chờ duyệt"}
                  </span>
                  {item.reviewStatus === "auto_approved" && (
                    <span className="agent-admin__status status-ai-reviewed">
                      AI duyệt
                    </span>
                  )}
                </div>
              </div>

              {isEditing ? (
                <div className="agent-admin__memory-edit-grid">
                  <label className="agent-admin__review-field">
                    <span>Tên bài học</span>
                    <input
                      maxLength={220}
                      type="text"
                      value={draft?.title ?? ""}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, { title: event.target.value })
                      }
                    />
                  </label>
                  <label className="agent-admin__review-field">
                    <span>Nhóm lỗi</span>
                    <select
                      value={draft?.category ?? item.category}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, {
                          category: event.target.value as LearningJournalItem["category"],
                        })
                      }
                    >
                      {Object.entries(categoryLabel).map(([value, label]) => (
                        <option key={value} value={value}>{label}</option>
                      ))}
                    </select>
                  </label>
                  <label className="agent-admin__review-field agent-admin__review-field--full">
                    <span>AI đã học được gì?</span>
                    <textarea
                      maxLength={3000}
                      rows={3}
                      value={draft?.summary ?? ""}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, { summary: event.target.value })
                      }
                    />
                  </label>
                  <label className="agent-admin__review-field agent-admin__review-field--full">
                    <span>Quy tắc tránh lặp lại</span>
                    <textarea
                      maxLength={3000}
                      rows={3}
                      value={draft?.preventionRule ?? ""}
                      onChange={(event) =>
                        updateDraft(item.learningJournalId, { preventionRule: event.target.value })
                      }
                    />
                  </label>
                </div>
              ) : (
                <div className="agent-admin__memory-body learning-journal-safe__body">
                  <div>
                    <strong>AI đã học được gì?</strong>
                    <p>{item.summary}</p>
                  </div>
                  <div>
                    <strong>Quy tắc tránh lặp lại</strong>
                    <p>{item.preventionRule}</p>
                  </div>
                </div>
              )}

              <div className="agent-admin__memory-actions learning-journal-safe__actions">
                {isEditing ? (
                  <>
                    <button
                      className="learning-journal-safe__action learning-journal-safe__action--approve"
                      disabled={busy === `learning-journal-save-${item.learningJournalId}` || !activeDraft}
                      onClick={() =>
                        onSave(
                          item.learningJournalId,
                          draft ?? {
                            title: item.title,
                            summary: item.summary,
                            preventionRule: item.preventionRule,
                            category: item.category,
                          },
                        ).then(() => setEditingId(null))
                      }
                      type="button"
                    >
                      <Save aria-hidden="true" size={15} strokeWidth={2} />
                      Lưu thay đổi
                    </button>
                    <button
                      className="learning-journal-safe__action learning-journal-safe__action--neutral"
                      onClick={() => setEditingId(null)}
                      type="button"
                    >
                      <X aria-hidden="true" size={15} strokeWidth={2} />
                      Hủy
                    </button>
                  </>
                ) : (
                  <>
                    {!isPromptActive && (
                      <button
                        className="learning-journal-safe__action learning-journal-safe__action--approve"
                        disabled={busy === `learning-journal-approve-${item.learningJournalId}`}
                        onClick={() => onApprove(item)}
                        type="button"
                      >
                        <Check aria-hidden="true" size={15} strokeWidth={2.25} />
                        {busy === `learning-journal-approve-${item.learningJournalId}`
                          ? "Đang duyệt..."
                          : "Duyệt"}
                      </button>
                    )}
                    <button
                      className="learning-journal-safe__action learning-journal-safe__action--neutral"
                      onClick={() => startEdit(item)}
                      type="button"
                    >
                      <Pencil aria-hidden="true" size={14} strokeWidth={2} />
                      Sửa
                    </button>
                  </>
                )}
                <button
                  className="learning-journal-safe__action learning-journal-safe__action--danger"
                  disabled={busy === `learning-journal-delete-${item.learningJournalId}`}
                  onClick={() => onDelete(item)}
                  type="button"
                >
                  <Trash2 aria-hidden="true" size={14} strokeWidth={2} />
                  Xóa bài học
                </button>
              </div>
            </article>
          );
        })}

        {!items.length && (
          <div className="agent-admin__empty">
            Chưa có bài học tự động nào. Khi AI bị người dùng sửa hoặc phát hiện mình hiểu sai,
            bài học đã khử dữ liệu cá nhân sẽ xuất hiện ở đây.
          </div>
        )}
      </div>
    </section>
  );
}
