analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3546466,"name"\:"Cellphone Shop Trial \#3546466","teamId"\:3551462,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3542980,"autoIntegrate"\:false,"sampleProject"\:false,"accountId"\:null}
analytics.team={"id"\:3551462,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=false
