import { useCallback, useEffect, useState } from 'react'
import { api } from '@/lib/api'
import { useAuthStore } from '@/store/authStore'
import './DeceasedFamilyPage.css'

type Profile = { id:number; plotId:number; plotCode?:string; fullName:string; dateOfDeath?:string; verificationStatus:string; rejectionReason?:string }
type Family = { id:number; name:string; status:string; role?:string }
type Invitation = { id:number; familyName:string; status:string }
type Permission = { id:number; userId:number; resourceType:string; resourceId:number; action:string }
const unwrap=<T,>(r:{data:unknown}):T=>{const b=r.data as {data?:T};return b?.data??r.data as T}
const errorText=(e:unknown)=>{const x=e as {response?:{data?:{message?:string|string[]}}};const m=x.response?.data?.message;return Array.isArray(m)?m.join(', '):m??'Không thể thực hiện yêu cầu.'}

export default function DeceasedFamilyPage(){
 const role=useAuthStore(s=>s.role),admin=role==='admin';const [profiles,setProfiles]=useState<Profile[]>([]),[families,setFamilies]=useState<Family[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[permissions,setPermissions]=useState<Permission[]>([]);const [familyId,setFamilyId]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const run=async(fn:()=>Promise<void>,ok:string)=>{setBusy(true);setError('');setMessage('');try{await fn();setMessage(ok)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const load=useCallback(async()=>{try{const r=await api.get(admin?'/admin/deceased':'/deceased');const d=unwrap<{items?:Profile[]}|Profile[]>(r);setProfiles(Array.isArray(d)?d:d.items??[]);if(!admin){const [f,i]=await Promise.all([api.get('/families'),api.get('/my/family-invitations')]);setFamilies(unwrap<Family[]>(f));setInvites(unwrap<Invitation[]>(i))}}catch(e){setError(errorText(e))}},[admin])
 useEffect(()=>{void load()},[load])
 const selectFamily=async(id:number)=>{setFamilyId(id);try{setPermissions(unwrap<Permission[]>(await api.get(`/families/${id}/permissions`)))}catch(e){setError(errorText(e));setPermissions([])}}
 return <div className="df-page"><header className="df-hero"><div><span>KHÔNG GIAN TƯỞNG NIỆM</span><h1>{admin?'Quản trị hồ sơ người đã khuất':'Hồ sơ người đã khuất & gia đình'}</h1><p>{admin?'Cấu hình sức chứa lô và kiểm duyệt hồ sơ.':'Quản lý hồ sơ, gia đình, lời mời và quyền chia sẻ.'}</p></div><button onClick={()=>void load()}>Làm mới</button></header>{error&&<div className="df-alert error">{error}</div>}{message&&<div className="df-alert ok">{message}</div>}
 {admin?<div className="df-grid"><SimpleForm title="Cấu hình sức chứa lô" fields={[['plotId','ID lô','number'],['capacity','Capacity','number']]} onSubmit={(d,f)=>run(async()=>{await api.patch(`/admin/plots/${Number(d.get('plotId'))}/deceased-capacity`,{capacity:Number(d.get('capacity'))});f.reset()},'Đã cập nhật capacity.')}/><ProfileList profiles={profiles} admin busy={busy} action={(id,a)=>void run(async()=>{if(a==='verify')await api.patch(`/admin/deceased/${id}/verify`);else{const reason=prompt('Lý do từ chối?');if(!reason)return;await api.patch(`/admin/deceased/${id}/reject`,{reason})}await load()},a==='verify'?'Đã xác minh.':'Đã từ chối.')} /></div>
 :<><div className="df-grid"><form className="df-card" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),f=e.currentTarget;void run(async()=>{await api.post('/deceased',{plotId:Number(d.get('plotId')),fullName:d.get('fullName'),dateOfBirth:d.get('dateOfBirth')||undefined,dateOfDeath:d.get('dateOfDeath')||undefined,burialDate:d.get('burialDate')||undefined,hometown:d.get('hometown')||undefined,biography:d.get('biography')||undefined});f.reset();await load()},'Đã tạo hồ sơ chờ xác minh.')}}><h2>Tạo hồ sơ</h2><Field n="plotId" l="ID lô đang sở hữu" t="number"/><Field n="fullName" l="Họ và tên"/><Field n="dateOfBirth" l="Ngày sinh" t="date" optional/><Field n="dateOfDeath" l="Ngày mất" t="date" optional/><Field n="burialDate" l="Ngày an táng" t="date" optional/><Field n="hometown" l="Quê quán" optional/><label>Tiểu sử<textarea name="biography" rows={3}/></label><button disabled={busy}>Tạo hồ sơ</button></form><ProfileList profiles={profiles} busy={busy} action={(id)=>void run(async()=>{await api.delete(`/deceased/${id}`);await load()},'Đã xóa mềm hồ sơ.')}/></div>
 <div className="df-family"><div className="df-card"><SimpleForm title="Tạo nhóm gia đình" fields={[["name","Tên nhóm","text"]]} onSubmit={(d,f)=>run(async()=>{await api.post('/families',{name:d.get('name')});f.reset();await load()},'Đã tạo gia đình.')}/><div className="df-list">{families.map(f=><button className={familyId===f.id?'selected':''} key={f.id} onClick={()=>void selectFamily(f.id)}><b>{f.name}</b><small>#{f.id} · {f.status} · {f.role}</small></button>)}</div></div><FamilyPanel familyId={familyId} permissions={permissions} busy={busy} run={run} reload={async()=>{await load();if(familyId)await selectFamily(familyId)}}/><div className="df-card"><h2>Lời mời của tôi</h2><div className="df-list">{invites.length===0&&<p>Chưa có lời mời.</p>}{invites.map(i=><article key={i.id}><b>{i.familyName}</b><small>#{i.id} · {i.status}</small>{i.status==='pending'&&<div><button onClick={()=>void run(async()=>{await api.patch(`/family-invitations/${i.id}/accept`);await load()},'Đã chấp nhận lời mời.')}>Chấp nhận</button><button className="muted" onClick={()=>void run(async()=>{await api.patch(`/family-invitations/${i.id}/reject`);await load()},'Đã từ chối.')}>Từ chối</button></div>}</article>)}</div></div></div></>}
 </div>
}
function Field({n,l,t='text',optional=false}:{n:string;l:string;t?:string;optional?:boolean}){return <label>{l}<input name={n} type={t} min={t==='number'?1:undefined} required={!optional}/></label>}
function SimpleForm({title,fields,onSubmit}:{title:string;fields:string[][];onSubmit:(d:FormData,f:HTMLFormElement)=>Promise<void>}){return <form className="df-card" onSubmit={e=>{e.preventDefault();void onSubmit(new FormData(e.currentTarget),e.currentTarget)}}><h2>{title}</h2>{fields.map(([n,l,t])=><Field key={n} n={n} l={l} t={t}/>) }<button>Lưu</button></form>}
function ProfileList({profiles,admin,busy,action}:{profiles:Profile[];admin?:boolean;busy:boolean;action:(id:number,a:'verify'|'reject')=>void}){return <div className="df-card"><h2>Danh sách hồ sơ</h2><div className="df-list">{profiles.length===0&&<p>Chưa có hồ sơ.</p>}{profiles.map(p=><article key={p.id}><div><span className="df-status">{p.verificationStatus}</span><h3>{p.fullName}</h3><small>Lô {p.plotCode??`#${p.plotId}`} · Ngày mất: {p.dateOfDeath||'—'}</small>{p.rejectionReason&&<p>{p.rejectionReason}</p>}</div><div>{admin&&p.verificationStatus==='pending_verification'?<><button disabled={busy} onClick={()=>action(p.id,'verify')}>Xác minh</button><button className="muted" onClick={()=>action(p.id,'reject')}>Từ chối</button></>:!admin&&<button className="danger" onClick={()=>action(p.id,'reject')}>Xóa</button>}</div></article>)}</div></div>}
function FamilyPanel({familyId,permissions,busy,run,reload}:{familyId:number|null;permissions:Permission[];busy:boolean;run:(f:()=>Promise<void>,m:string)=>Promise<void>;reload:()=>Promise<void>}){if(!familyId)return <div className="df-card"><h2>Quản lý nhóm</h2><p>Chọn một nhóm để thao tác.</p></div>;const post=(path:string,data:object,msg:string)=>run(async()=>{await api.post(path,data);await reload()},msg);return <div className="df-card"><h2>Quản lý nhóm #{familyId}</h2><div className="df-tools"><SimpleForm title="Liên kết lô" fields={[["plotId","ID lô","number"]]} onSubmit={d=>post(`/families/${familyId}/plots`,{plotId:Number(d.get('plotId'))},'Đã thêm lô.')}/><SimpleForm title="Mời thành viên" fields={[["userId","User ID","number"]]} onSubmit={d=>post(`/families/${familyId}/invitations`,{inviteeUserId:Number(d.get('userId'))},'Đã gửi lời mời.')}/><form className="df-card" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void post(`/families/${familyId}/permissions`,{memberUserId:Number(d.get('userId')),resourceType:d.get('resourceType'),resourceId:Number(d.get('resourceId')),action:d.get('action')},'Đã cấp quyền.')}}><h2>Cấp quyền</h2><Field n="userId" l="User ID" t="number"/><label>Tài nguyên<select name="resourceType"><option value="deceased_profile">Hồ sơ</option><option value="plot">Lô</option><option value="service_order">Đơn dịch vụ</option></select></label><Field n="resourceId" l="ID tài nguyên" t="number"/><label>Action<select name="action"><option>view_profile</option><option>view_plot</option><option>view_service_history</option><option>order_service</option></select></label><button disabled={busy}>Cấp quyền</button></form></div><h3>Quyền hiệu lực</h3><div className="df-list">{permissions.map(p=><article key={p.id}><span>User #{p.userId}: {p.action} · {p.resourceType} #{p.resourceId}</span><button className="danger" onClick={()=>void run(async()=>{await api.delete(`/families/${familyId}/permissions/${p.id}`);await reload()},'Đã thu hồi quyền.')}>Thu hồi</button></article>)}</div><div className="df-actions"><button className="muted" onClick={()=>void post(`/families/${familyId}/disable`,{},'Đã disable và thu hồi quyền.')}>Disable</button><button onClick={()=>void post(`/families/${familyId}/enable`,{},'Đã enable; quyền cũ không được phục hồi.')}>Enable</button></div></div>}
